// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for ios - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDdiDmN1NHWkOgwVD0brC7BEQ7pLSYf2tc',
    appId: '1:155898379256:web:5402e1b7d193e4a7db340d',
    messagingSenderId: '155898379256',
    projectId: 'vista-38ea9',
    authDomain: 'vista-38ea9.firebaseapp.com',
    databaseURL: 'https://vista-38ea9-default-rtdb.firebaseio.com',
    storageBucket: 'vista-38ea9.appspot.com',
    measurementId: 'G-ZBGD9V6MK0',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyArhziKNcgba_JlAgh5_Yh0QBhrByw7k9o',
    appId: '1:155898379256:android:fc6671859d16db13db340d',
    messagingSenderId: '155898379256',
    projectId: 'vista-38ea9',
    databaseURL: 'https://vista-38ea9-default-rtdb.firebaseio.com',
    storageBucket: 'vista-38ea9.appspot.com',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDO8GV3GkwaBS-n55DNLXj5e2KL0ZhLzes',
    appId: '1:155898379256:ios:937cc529440affaadb340d',
    messagingSenderId: '155898379256',
    projectId: 'vista-38ea9',
    databaseURL: 'https://vista-38ea9-default-rtdb.firebaseio.com',
    storageBucket: 'vista-38ea9.appspot.com',
    iosClientId: '155898379256-ll16lngrdugosh918lug4431cl63o0g0.apps.googleusercontent.com',
    iosBundleId: 'com.example.vista',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDdiDmN1NHWkOgwVD0brC7BEQ7pLSYf2tc',
    appId: '1:155898379256:web:7f2e1808070e29e3db340d',
    messagingSenderId: '155898379256',
    projectId: 'vista-38ea9',
    authDomain: 'vista-38ea9.firebaseapp.com',
    databaseURL: 'https://vista-38ea9-default-rtdb.firebaseio.com',
    storageBucket: 'vista-38ea9.appspot.com',
    measurementId: 'G-EK2RVBWN5D',
  );
}
