// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for ios - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDIZG9Yo9Ntgd8kCA74cXFkcVN5b3fqNPU',
    appId: '1:136464011660:web:14bea54c1c4d689e6606a9',
    messagingSenderId: '136464011660',
    projectId: 'vista-9e65c',
    authDomain: 'vista-9e65c.firebaseapp.com',
    storageBucket: 'vista-9e65c.appspot.com',
    measurementId: 'G-GPX01XZLRB',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDKI2Zb6W4gWuNc6khSsBqjDval5IzP6vg',
    appId: '1:136464011660:android:2bdcdc4e66cc72966606a9',
    messagingSenderId: '136464011660',
    projectId: 'vista-9e65c',
    storageBucket: 'vista-9e65c.appspot.com',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAt6HyoWg2vwbM_eBNgdEkd5YZgksHpCrA',
    appId: '1:136464011660:ios:d16cd2e0374c16986606a9',
    messagingSenderId: '136464011660',
    projectId: 'vista-9e65c',
    storageBucket: 'vista-9e65c.appspot.com',
    iosClientId: '136464011660-bcuejnvm3nidul6k5dc8fo59e6fms2cv.apps.googleusercontent.com',
    iosBundleId: 'com.example.vista',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDIZG9Yo9Ntgd8kCA74cXFkcVN5b3fqNPU',
    appId: '1:136464011660:web:d67bbceee95531066606a9',
    messagingSenderId: '136464011660',
    projectId: 'vista-9e65c',
    authDomain: 'vista-9e65c.firebaseapp.com',
    storageBucket: 'vista-9e65c.appspot.com',
    measurementId: 'G-P437QSCG3F',
  );

}